name: release
on:
  release:
    types: [published]
jobs:
  publish-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
      - name: Build CSS
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: "true"
        run: |
          tox -e release
